# in .cargo/config.toml

# [target.'cfg(target_os = "linux")']
# rustflags = ["-C", "link-arg=-nostartfiles"]

# [target.'cfg(target_os = "windows")']
# rustflags = ["-C", "link-args=/ENTRY:_start /SUBSYSTEM:console"]

# [target.'cfg(target_os = "macos")']
# rustflags = ["-C", "link-args=-e __start -static -nostartfiles"]

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "i686-unknown-none.json"

[target.i686-unknown-none]
rustflags = ["-C", "link-args=--image-base=0x30000 -Ttext=0x30400"]

# [target.i686-unknown-none]
# rustflags = ["-C", "link-args=-Tsrc/linker.ld"]